### PR TITLE
fix(#1754): give processLuts external linkage + fuzz-harnessable entry

### LINKED ISSUE #1754: Bisect: 2d5cc8d processLuts
## Maintainer Summary
2026-07-21 12:34:50 UTC

### Build Log
```
Profile visualization fuzzers:
  Compiling MiniTIFF.o + MiniSVG.o + MiniPDF.o...
/home/xss/research/cfl/icc_profilevisualize_fuzzer.cpp:130:15: error: use of undeclared identifier 'processLuts'
  130 |         (void)processLuts(profile, profilePath);
      |               ^~~~~~~~~~~
1 error generated.
  [FAIL] icc_profilevisualize_fuzzer FAILED

```

### PR DESCRIPTION
**Pull request by colourbill-ctrl**
Fixes #1754.

## Problem
`processLuts()` in `Tools/CmdLine/IccProfilePlot/iccProfileVisualize.cpp` was `static` (internal linkage) with no declaration of its own, reachable only from that translation unit's `main()`. An out-of-line driver — xsscx's `icc_profilevisualize_fuzzer.cpp` — calling `processLuts(profile, profilePath)` fails at compile with `use of undeclared identifier 'processLuts'`, and would not have linked even with a local prototype because internal linkage keeps the symbol private to the TU.

Bisected to `2d5cc8d` (#1517), which introduced `processLuts` as the tool's private driver.

## Fix
Three coordinated changes, all in our-owned `IccProfilePlot/`:

1. **New `iccProfileVisualize.hpp`** declaring `int processLuts(CIccProfile*, const char*)`. The `.cpp` includes it so definition and declaration stay in sync (a signature drift now fails the build instead of rotting a copy-pasted prototype). Forward-declares `CIccProfile` per the sibling `IccVizModel.hpp` convention.
2. **Dropped `static`** from the definition → external linkage, so the symbol is linkable from another translation unit. This is the actual enabler; a header alone would fix only the compile error, not the link.
3. **Guarded `main()`** behind `#ifndef ICC_PROFILEVISUALIZE_NO_MAIN`. A harness that links this object for `processLuts()` supplies its own entry point (libFuzzer provides `main`); the guard lets it build with `-DICC_PROFILEVISUALIZE_NO_MAIN` to drop ours and avoid a duplicate-`main` link clash. The normal tool build leaves the macro undefined and compiles `main()` unchanged.

No CMake change: the new header sits alongside existing sources already on the target's include path.

## Verification
- Normal `iccProfileVisualizePlot` build compiles + links clean.
- `nm` on the normal object: `T processLuts` (was `t`/static) and `T main`.
- `nm` on the harness-mode object (`-DICC_PROFILEVISUALIZE_NO_MAIN`): `T processLuts`, **no `main`**.
- CLI smoke test unchanged: no-args prints usage (exit 0); a real profile drives PDF/TIFF output (exit 0).

### CODE REVIEW

File: Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+// Only a CIccProfile* is named in the interface, so forward-declare it rather
+// than pull in IccProfile.h - matches IccVizModel.hpp and keeps this header
+// cheap for a harness that already has its own ICC includes.
+class CIccProfile;
+
+// Render every visualization pIcc supports to PDF/TIFF written alongside
+// profilePath (used to derive the output basename). Returns the count of
+// output items produced; 0 means the profile yielded nothing to draw, which
+// the CLI treats as a per-file failure.
+int processLuts(CIccProfile *pIcc, const char *profilePath);
```
[the remark this answers is not in the document]
Comment (xsscx) [reply Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp:99]: @colourbill-ctrl Make the changes you want long term and I can adjust the harnesses to your corrections

File: Tools/CmdLine/IccProfilePlot/iccProfileVisualize.cpp [hunk 2]
```diff
@@ -1496,6 +1503,13 @@ void printUsage(void)
 
 /******************************************************************************/
 
+// The CLI entry point is just an argv loop around processLuts(). A harness that
+// links this object for processLuts() supplies its own entry point (libFuzzer
+// provides main; a regression driver defines its own), so build that harness
+// with -DICC_PROFILEVISUALIZE_NO_MAIN to drop ours and avoid a duplicate-main
+// link error. The normal tool build leaves the macro undefined and compiles
+// main() unchanged.
+#ifndef ICC_PROFILEVISUALIZE_NO_MAIN
```
[the remark this answers is not in the document]
Comment (xsscx) [reply Tools/CmdLine/IccProfilePlot/iccProfileVisualize.cpp:1512]: @colourbill-ctrl Make the changes you want long term and I can adjust the harnesses to your corrections
Attempting to onboard the AFL/CFL Workflows and hit these issues.

Thank You

**Comment by colourbill-ctrl** [comment]
@ChrisCoxArt — apologies, and a heads-up: I accidentally force-pushed over your "Update branch" merge on this PR, then restored it. The branch is back at `c9f75659` exactly as you left it — current with master (incl. #1752), with the #1754 change intact. I've corrected my process (fetch + check the branch tip before any push) so it won't recur, and I'll leave the branch to you from here. Thanks for updating it.

**Comment by ChrisCoxArt** [comment]
I was just updating it so it was clear to merge once you responded to the AI "conversations"

**Review by xsscx — CHANGES_REQUESTED** [review]
I will regroup on this Issue and add to ci-qa-flags for testing ideas

File: Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (colourbill-ctrl) [reply Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp:99]: Confirming the long-term direction so the harness can point the right way: `processLuts` lives in `Tools/CmdLine/IccProfilePlot/` and should stay there — it was introduced in that directory by #1517 (`2d5cc8d`, the bisect commit for this issue) and has never existed in the legacy `Tools/CmdLine/IccProfileVisualize/` copy (that file has no `processLuts` symbol at all). So the harness wants `VISUAL_SRC_DIR` / include flags on `IccProfilePlot/`, `#include "iccProfileVisualize.hpp"`, and `iccProfileVisualize.cpp` + `IccVizModel.cpp` compiled with `-DICC_PROFILEVISUALIZE_NO_MAIN`. This PR supplies exactly that extern symbol + public header + main-guard.

File: Tools/CmdLine/IccProfilePlot/iccProfileVisualize.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (colourbill-ctrl) [reply Tools/CmdLine/IccProfilePlot/iccProfileVisualize.cpp:1512]: I pushed a concrete version of this as `353cd00b`: an in-repo CTest (`iccdev.iccviz-processluts-harness`) that compiles `iccProfileVisualize.cpp` with `-DICC_PROFILEVISUALIZE_NO_MAIN` and calls `processLuts()` through the header, driven on the sRGB v4 LUT profile. The build itself is the guard — reverting `processLuts` to `static` fails to compile via the header self-include, and dropping the `main()` guard duplicates `main()`. It also moves `printUsage()` inside the guard so the `NO_MAIN` build is `-Werror`-clean. Verified locally, including a negative proof (re-adding `static` breaks the build).

Saw your note about regrouping the testing on `ci-qa-flags` — please treat `353cd00b` purely as raw material. Happy to move it to `ci-qa-flags`, reshape it toward the AFL/CFL harness, or drop it entirely; your call on the testing direction.

File: Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+// Only a CIccProfile* is named in the interface, so forward-declare it rather
+// than pull in IccProfile.h - matches IccVizModel.hpp and keeps this header
+// cheap for a harness that already has its own ICC includes.
+class CIccProfile;
+
+// Render every visualization pIcc supports to PDF/TIFF written alongside
+// profilePath (used to derive the output basename). Returns the count of
+// output items produced; 0 means the profile yielded nothing to draw, which
+// the CLI treats as a per-file failure.
```
[the remark this answers is not in the document]
Comment (colourbill-ctrl) [reply Tools/CmdLine/IccProfilePlot/iccProfileVisualize.hpp]: The autofix (`c4575486`) reads accurately — verified at `iccProfileVisualize.cpp:1390`: a failed `WriteTIFF()` logs to stderr and `++outputItems` still runs, so a raster descriptor is counted as rendered (its raster is produced in-memory) even when the file write fails. Whether a failed write should instead not count toward the total is a behavior question I'd keep separate from this linkage fix.

**Comment by xsscx** [comment]
## Blocking findings
2026-07-22 00:38:27 UTC
1. It does not fix #1754 today. CFL includes the legacy  IccProfileVisualize/iccProfileVisualize.cpp  directly ( cfl/icc_profilevisualize_fuzzer.cpp:56-57 ), while the PR exports a function from  IccProfilePlot . The same compile failure remains.
2. Harness mode fails strict Clang. Defining  ICC_PROFILEVISUALIZE_NO_MAIN  leaves  printUsage()  unused, triggering  -Werror=unused-function .
3. There is no reusable target.  Build/Cmake/Tools/IccProfilePlot/CMakeLists.txt:28-41  builds everything only into an executable. Consumers must manually reconstruct its private source list.
4. The “public” header is not actually consumable. It is not installed/exported and exposes a file-writing CLI orchestration function rather than a stable core API.
5. No regression proves the intended integration. CI never compiles a second translation unit against the new API.

**Comment by colourbill-ctrl** [comment]
@xsscx — all five findings accepted, thanks for the detailed breakdown.

You're right that this exports from `IccProfilePlot` while CFL compiles the legacy `IccProfileVisualize/` copy, so it never fixed the actual build (#1), and that the NO_MAIN path left `printUsage()` unused with no reusable target or regression proving the integration (#2/#5). The #3/#4 point — that a file-writing CLI orchestration function behind an un-exported header isn't a consumable API — is the right call, and #1769 is now doing exactly that (`dataModel`/`dataToJSON`/`dataToPDF`/`vizShared`), which is the proper home for this.

One correction for the record: my earlier reply here cited `353cd00b` (an in-repo harness CTest), but the branch was deleted on close so that commit didn't persist — please disregard it. Happy to help on the #1769 work or the CFL retarget if useful; otherwise I'll leave this closed and follow your lead on `ci-qa-flags`.

**Comment by xsscx** [comment]
## Notes
2026-08-05 00:36:14 UTC

This PR will be rebased and Fuzzed., Its needed, but at the time appeared too invasive for the existing stable code to add a Fuzzing Harness. Now that the Apply* Bugs have been addressed my plan is to rebase this PR on master:HEAD and continue Fuzzing. 

Probably just re-open and Merge once stable @colourbill-ctrl will circle back on this probably 24-48 hours.

TODO @xsscx
