### PR TITLE
fix(#1888): let regression tests link exported IccProfLib data on Windows

### LINKED ISSUE #1888: Bug: exported IccProfLib global variables do not link on Windows shared builds — five ad-hoc workarounds, no documented rule
Found while adding a CTest for #1809 (PR #1887), whose first push failed Windows CI only. The
immediate breakage is fixed in that PR by avoiding the symbols, but the underlying gap is
general, already worked around ad hoc in five places, and has no documented rule — so each new
consumer rediscovers it through a red Windows run that no Linux or macOS pre-flight can predict.

## Exported global *variables* do not resolve on Windows shared builds

`WINDOWS_EXPORT_ALL_SYMBOLS` auto-exports **functions**. Global **data** symbols still require
explicit `__declspec(dllexport)` / `dllimport`, and IccProfLib does not supply it on MSVC:

| Step | Where | Effect |
|---|---|---|
| `ENABLE_SHARED_LIBS` defaults `ON` | `Build/Cmake/CMakeLists.txt:464` | Windows links `IccProfLib2` as a DLL |
| `ICCPROFLIBDLL_EXPORTS` is deliberately **not** defined on MSVC | `Build/Cmake/IccProfLib/CMakeLists.txt:180-181` (`if(NOT MSVC)`) | `ICCPROFLIB_API` expands to nothing in the library TU |
| `WINDOWS_EXPORT_ALL_SYMBOLS ON` instead | `Build/Cmake/IccProfLib/CMakeLists.txt:188` | functions exported, data not |
| Consumer defines neither `..._EXPORTS` nor `..._IMPORTS` | `IccProfLib/IccProfLibConf.h:95-104` | `ICCPROFLIB_API` empty → direct data reference, no `__imp_` indirection |

Functions therefore thunk fine while variables fail to link. Linux and macOS are unaffected: there
is no import-library model, and `-fvisibility=hidden` is intentionally not used for shared builds
(`Build/Cmake/IccProfLib/CMakeLists.txt:191-196`).

The repository already records the root cause in that same file at `:192-193`:

> IccProfLib has incomplete ICCPROFLIB_API annotations (~308 partial uses across 43 headers)

## Observed failure

First push of PR #1887 added a regression test referencing `icMsgValidateWarning`,
`icMsgValidateCriticalError` and `icMsgValidateInformation`. Two workflows, four jobs, all Windows:

```
mpe-empty-identity.obj : error LNK2019: unresolved external symbol
  "char const * const icMsgValidateWarning" (?icMsgValidateWarning@@3PEBDEB) referenced in function main
  ... same for icMsgValidateCriticalError, icMsgValidateInformation
fatal error LNK1120: 3 unresolved externals
```

`ci-pr-action` reported `LNK2001` (Debug) and `ci-json-python` `LNK2019` (Release); same three
symbols. ctest then surfaced it as `39 - iccdev.mpe-empty-identity (Not Run)`, i.e. a **build**
failure presenting as a test failure.

## Affected surface

All nine exported global variables in the public headers:

| Symbol | Header |
|---|---|
| `g_pIccMatrixSolver` | `IccProfLib/IccSolve.h:114` |
| `g_pIccMatrixInverter` | `IccProfLib/IccSolve.h:176` |
| `icD50XYZ[3]` | `IccProfLib/IccUtil.h:136` |
| `icD50XYZxx[3]` | `IccProfLib/IccUtil.h:137` |
| `icMsgValidateWarning` | `IccProfLib/IccUtil.h:200` |
| `icMsgValidateNonCompliant` | `IccProfLib/IccUtil.h:201` |
| `icMsgValidateCriticalError` | `IccProfLib/IccUtil.h:202` |
| `icMsgValidateInformation` | `IccProfLib/IccUtil.h:203` |
| `icInfo` | `IccProfLib/IccUtil.h:429` |

`g_pIccMatrixSolver` / `g_pIccMatrixInverter` are documented extension points — a downstream
consumer installing a custom solver against the Windows DLL hits this directly.

## Existing workarounds — two incompatible patterns, five sites, no stated rule

**Pattern A — link the static library instead.** Identical `IF(WIN32 AND ENABLE_SHARED_LIBS AND
TARGET IccProfLib2-static)` guard, copied three times:

| Target | Location |
|---|---|
| `iccDumpProfile` | `Build/Cmake/Tools/IccDumpProfile/CMakeLists.txt:6-10` |
| `iccProfilePlot` | `Build/Cmake/Tools/IccProfilePlot/CMakeLists.txt:8-12` |
| `iccDumpProfileGui` | `Build/Cmake/Tools/wxProfileDump/CMakeLists.txt:31-35` |

The wxProfileDump comment states the cause plainly: *"references exported data symbols
(icMsgValidateWarning, icMsgValidateNonCompliant) that WINDOWS_EXPORT_ALL_SYMBOLS cannot export."*

**Pattern B — do not reference the symbol; hard-code its value.**

| Test | Location |
|---|---|
| `pawg-q4-xyz-pcs-decode.cpp` | `:64-69` — literal D50 instead of `icD50XYZ` |
| `mpe-empty-identity.cpp` | `:61-68` — literal prefixes instead of `icMsgValidate*` (added by PR #1887) |

The two patterns disagree about whether referencing library data from a test is legitimate, and
nothing tells an author which to use — or that the problem exists at all.

## Why regression tests keep hitting it

`iccdev_add_regression_executable` links `${TARGET_LIB_ICCPROFLIB}` unconditionally
(`Build/Cmake/Testing/CMakeLists.txt:47-50`, then per-test `target_link_libraries`). It has **no**
static-library fallback, unlike the three Tools targets above. So the Tools are protected and the
tests are not, even though both link the same library.

## Latent trap

`.github/ci/regression/pcc-zero-illuminant.cpp:23-25` references `icD50XYZ[]` directly and does
**not** break today only because it is driven by a bash script test
(`iccdev_add_script_test` → `.github/scripts/iccdev-pcc-zero-illuminant-regression-tests.sh`,
registered at `Build/Cmake/Testing/CMakeLists.txt:3036-3041`) that does not run on the MSVC leg.
Converting it to `iccdev_add_regression_executable` — the normal direction of travel for these
tests — would break Windows CI with no source change.

## Suggested resolutions

Not mutually exclusive; (1) is the cheap containment and (3) is the actual fix.

1. **Give `iccdev_add_regression_executable` the same static fallback the Tools already have.**
   One place, matches established in-tree precedent, unblocks tests that legitimately want to
   assert on library data. Does not fix downstream consumers.
2. **Document the constraint** in `.github/ci/regression/README.md` and alongside the declarations
   in `IccUtil.h` / `IccSolve.h`, so the failure is anticipated rather than discovered in CI.
   Worth doing regardless of which code path is chosen.
3. **Export the data properly**: define `ICCPROFLIBDLL_EXPORTS` for the MSVC shared build and have
   consumers of the DLL compile with `ICCPROFLIBDLL_IMPORTS` so `ICCPROFLIB_API` resolves to
   `dllimport`. This is the real fix and removes both workaround patterns, but it touches the
   export model that `:191-196` says is deliberately incomplete, so it needs a maintainer decision
   before anyone starts.

Happy to take whichever direction you prefer. My inclination is (1) + (2) now as a contained
change with a CTest that links a library data symbol and would have caught the #1887 break, and
(3) separately if you want the export model corrected — but the choice between containment and a
real export fix is yours.

## Environment

- master `31704d98`
- Failing runs: `ci-pr-action` 30398717069, `ci-json-python` 30398717039 (PR #1887, commit `6a84cffd`)
- Green after the workaround: same workflows at `7a45f18d`, `iccdev.mpe-empty-identity` passes on
  `Windows MSVC + ClangCL` (Test #40)

### PR DESCRIPTION
**Pull request by colourbill-ctrl**
Fixes #1888. Implements paths (1) and (2) per your ruling on the issue; path (3), correcting the export model itself, is not attempted.

## The defect

A regression test that references an exported IccProfLib global **variable** could not be linked on a Windows shared build. `ENABLE_SHARED_LIBS` defaults `ON`, so the library is `IccProfLib2.dll`, and its exports come from `WINDOWS_EXPORT_ALL_SYMBOLS` rather than `__declspec` annotations — MSVC is deliberately excluded from the `ICCPROFLIBDLL_EXPORTS` definition (`Build/Cmake/IccProfLib/CMakeLists.txt:180-181`), the arrangement introduced in #764.

That mechanism auto-exports functions but **not global data**, and IccProfLib carries no `dllexport`/`dllimport` on its variables. A consumer compiling with `ICCPROFLIB_API` empty emits a direct data reference with no `__imp_` indirection:

```
mpe-empty-identity.obj : error LNK2019: unresolved external symbol
  "char const * const icMsgValidateWarning" (?icMsgValidateWarning@@3PEBDEB)
fatal error LNK1120: 3 unresolved externals
```

Functions in the same headers thunk normally, which is why this stayed hidden until #1887 became the first regression test to touch library data. Linux and macOS have no import-library model, so a local pre-flight cannot catch it — only the Windows CI leg can.

## The change

`ICCDEV_TEST_LIB_ICCPROFLIB` resolves to `IccProfLib2-static` on Windows shared builds and to the normal target everywhere else — the same fallback `iccDumpProfile`, `iccProfilePlot` and `wxProfileDump` already carry.

### One deliberate deviation from the wording in the issue

I proposed putting the fallback inside `iccdev_add_regression_executable`. On implementation that turned out to be unsafe, so it is a separate opt-in target instead.

`IccXML2` and `IccJson` link `${TARGET_LIB_ICCPROFLIB}` **`PUBLIC`** (`Build/Cmake/IccXML/CMakeLists.txt:139,174`). A test linking one of those *and* the static IccProfLib would pull the library into the process twice — once inside the DLL, once in the executable — giving two copies of its globals. Applying the fallback to every regression executable would have introduced that for the tests that co-link IccXML, including the two that exist today.

So the rule is: tests linking IccProfLib alone may use the fallback; tests co-linking IccXML/IccJson must keep asserting on literal values. The documentation says this explicitly at each point where someone would need it.

## Documentation (path 2)

Per your `Known Defect` note, the constraint is now recorded in four places rather than only in a CMake comment:

- beside each affected declaration in `IccProfLib/IccUtil.h` and `IccProfLib/IccSolve.h`
- a new section in `.github/ci/regression/README.md` covering which fallback to choose and why
- a new **Shared library exports** section in `docs/build.md`, citing #764 as the origin of the design
- the `ICCDEV_TEST_LIB_ICCPROFLIB` definition itself

`IccSolve.h` now also points at `IccSetMatrixSolver()` / `IccSetMatrixInverter()` as the linkable way to install a custom solver against the DLL — these are the exported data most likely to be reached for by a downstream consumer, and the setters are functions, so they link normally.

## Test

`iccdev.proflib-exported-data-linkage`. Its primary value is that **it links at all on Windows**: drop the fallback and that leg fails here, rather than in whichever test next reaches for library data.

It also earns its place on every platform. Because tests co-linking IccXML cannot reference these symbols, they hard-code the values instead (`mpe-empty-identity.cpp`, `pawg-q4-xyz-pcs-decode.cpp`), and hard-coded copies drift silently. This pins the real globals, so a change to `icMsgValidateWarning` or `icD50XYZ` fails in one place that names the literals needing an update.

## A correction to the issue text

I wrote that nine exported globals were affected. It is **eight**.

`IccUtil.h:429` declares `icInfo`, but it is defined nowhere in the tree — `nm -DC libIccProfLib2.so` lists the other exported globals and not that one — so referencing it fails to link on **every** platform, not only Windows. Nothing in-tree uses it. I found this because the test would not link on Linux.

That is a dangling public declaration rather than an export problem, so it is out of scope here. I left the declaration in place, since removing public API surface is a separate decision for you, and added a note recording what it is. Happy to file it separately if you want it addressed.

## Verification

- Full build: 0 warnings
- CI's own strict gate (`-Wall -Wextra -Wpedantic -Werror -std=c++17`, Release): 0 warnings, 0 errors
- `ctest`: 123/124; the sole failure is `iccdev.spectral-tiff-preview` (`ModuleNotFoundError: No module named 'imagecodecs'`), a known local environment gap unrelated to this change
- ASAN+UBSAN with `ASAN_OPTIONS=detect_leaks=1`: clean
- Both link paths exercised locally: default shared (`ICCDEV_TEST_LIB_ICCPROFLIB = IccProfLib2`) and `-DENABLE_SHARED_LIBS=OFF` (`= IccProfLib2-static`, the target the Windows fallback selects)

The Windows behaviour itself is the one thing that cannot be verified locally — that is the nature of the defect, and this PR's CI run is the check.

### CODE REVIEW

**Review by xsscx — APPROVED** [review]
2026-07-28 23:15:07 UTC

**Comment by xsscx** [comment]
## PR Status
2026-07-28 23:15:59 UTC

This branch has conflicts that must be resolved

**Comment by xsscx** [comment]
## Conflict Resolution
2026-07-28 23:24:08 UTC

Take Ours & Theirs

**Comment by xsscx** [comment]
## Verified Stacked PR Working
2026-07-28 23:30:35 UTC

https://github.github.com/gh-stack/

Image


@colourbill-ctrl Try Stacked Prs when time permits

Great Work!!

Thank You
